/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.gabrielshanahan.onlyinputtypestest

import kotlin.internal.OnlyInputTypes

class App {
    inline infix fun <@OnlyInputTypes reified T, U : T> T.shouldBeOnlyInputTypes(any: U?) = println(T::class)
    inline infix fun <reified T, U : T> T.shouldBe(any: U?) = println(T::class)

    fun doTest() {
        "Hello" shouldBe 5
        "Hello" shouldBeOnlyInputTypes 5
    }
}

fun main(args: Array<String>) {
    App().doTest()
}
